filebeat.modules:

#=============================== Modules =================================

- module: elasticsearch
  server:
    enabled: true
  gc:
    enabled: true
  audit:
    enabled: true
  slowlog:
    enabled: true
  deprecation:
    enabled: true
- module: kibana
  log:
    enabled: true

#=========================== Filebeat inputs =============================

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/logs/*.log

setup.template.name: "filebeat-"
setup.template.pattern: "filebeat-*"
setup.dashboards.enabled: true

setup.kibana:
  host: http://kibana:5601
  username: elastic
  password: youpassword

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: elastic
  password: youpassword
  index: "filebeat-%{[beat.version]}-%{+yyyy.MM.dd}"
