version: '2'
services:
  elasticsearch:
    image: elasticsearch:7.8.0
    volumes:
     - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: youpassword
    networks:
     - elk
  filebeat:
    image: elastic/filebeat:7.8.0
    command: filebeat -e -strict.perms=false
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./data/external/:/usr/share/filebeat/logs
    networks:
      - elk
    links:
       - elasticsearch
       - kibana
  kibana:
    volumes:
      - ./kibana.yml:/usr/share/filebeat/filebeat.yml:ro
    image: elastic/kibana:7.8.0
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: youpassword
    ports:
      - 5601:5601
    networks:
      - elk
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
networks:
  elk:
    driver: bridge
